//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Murray_P1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JordanInventory
    {
        public string ItemStyleNum { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
        public string ProductCategoryCode { get; set; }
        public string ImageFile { get; set; }
    }
}
